M48
; DRILL file {KiCad (6.0.11)} date Thu Apr 20 22:04:12 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-20T22:04:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X6.225Y-4.275
X6.25Y-4.2
T2
X6.225Y-4.4094
X6.225Y-4.5094
T3
X5.0394Y-4.4094
X5.0394Y-4.5094
T0
M30
